site_name: DIYraman Documentation
site_url: https://docs.diyraman.com

docs_dir: docs


nav:
  - 00 - Start here:
      - Parts list (BOM): https://github.com/jacobbusshart/DIYraman/blob/main/bom/BOM.md
      - Introduction: Introduction.md

  - 01 - Build the basics:
      - Measuring light: "Spectrometer-Setup.md"
      - Dustproof workspace: "Dustproof-Workspace.md"
      - Core optical assembly: "Core-Assembly.md"

  - 02 - Calibrate & test:
      - Aligning with fluorescence: "Align-with-Fluorescence.md"
      - Software quick guide: "SpectrumStudio-Cheatsheet.md"

  - 03 - Upgrades:
      - DIY focus stage: "DIY-Linear-Stage.md"
      - Full build: "Full-Build.md"

theme:
  name: material
  language: en
  features:
      - navigation.instant
      - navigation.sections
      - navigation.expand
      - navigation.tracking
      - toc.integrate
      - toc.follow
      - search.suggest
      - search.highlight
      - content.code.copy
      - content.tabs.link
      - navigation.top
      - navigation.footer
      - header.autohide
  palette:
  - scheme: slate
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: default
    primary: black
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  font:
    text: KoHo                                  #formerly Inter, maybe this only for H1/H2
    code: JetBrains Mono
    
plugins:
  - search
  - callouts

repo_url: https://github.com/jacobbusshart/DIYraman
repo_name: DIYraman

markdown_extensions:
  - nl2br
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - extra.css